data:
    sample_rate: 8000
    segment: 4.0

model:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: 0
    mask_nonlinear: 'relu'

optim:
    type: 'Adam'
    lr: 0.001
    weight_decay: 0.0

solver:
    exp_name: 'debug'
    save_dir: './checkpoints/'
    max_save_num: 3
    log_dir: './logs/'
    epochs: 100
    start_epoch: 0
    resume: ""
    resume_optim: ""
    grad_clip: 5
    batch_size: 4
    num_workers: 4
    scheduler:
        use: True
        type: 'ReduceLROnPlateau'
        patience: 4

