# There is two perturbation need to be set in noisy student.
# First one can be set in 'input_transform' of 'solver', which stand for gaussian noise.
# Second one is set in 'sep_out_dropout' of 'model', which stand for dropout part.
# Choose one while training.
data:
    dset: 'wsj0'
    sample_rate: 8000
    segment: 4.0
    uns_dset: 'wsj0-vctk'
    uns_segment: 2.0

model:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: 0
    mask_nonlinear: 'softmax'
    sep_out_dropout: 0.1

optim:
    type: 'ranger'
    lr: 0.001
    weight_decay: 0.0

solver:
    exp_name: 'noisy_student-wsj0vctk-dropout01'
    save_dir: './checkpoints/'
    log_dir: './logs/'
    pretrained: ''
    pretrained_optim: False
    pretrained_teacher: './pretrained/baseline-softmax-wsj0-with_10epoch-2020_04_05_16_00_07/latest.pth'
    teacher_config: './pretrained/baseline-softmax-wsj0-with_10epoch-2020_04_05_16_00_07/config.yaml'
    max_save_num: 1
    epochs: 100
    start_epoch: 0
    resume_exp_name: ""
    resume_optim: False
    grad_clip: 5
    batch_size: 2
    num_workers: 4
    # hyperparameter for noisy student.
    # Only need to config scheduler for weight.
    ns:
        use: True
        scheduler:
            function: ramp
            start_step: 0
            end_step: 50
            start_value: 0
            end_value: 1.0
    scheduler:
        use: True
        type: 'ReduceLROnPlateau'
        patience: 4

