data:
    dset: 'wsj0'
    sample_rate: 8000
    segment: 4.0
    uns_dset: 'wsj0-vctk'
    uns_segment: 2.0

model:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: 0
    mask_nonlinear: 'softmax'
    sep_out_dropout: 0.1

optim:
    type: 'ranger'
    lr: 0.0001
    weight_decay: 0.0

solver:
    exp_name: 'pi_model-pertrub_dropout01-consistency_emb'
    save_dir: './checkpoints/'
    log_dir: './logs/'
    pretrained: './pretrained/baseline-softmax-wsj0-with_10epoch-2020_04_05_16_00_07/89_force.pth'
    pretrained_optim: False
    max_save_num: 1
    epochs: 10
    start_epoch: 0
    resume_exp_name: ""
    resume_optim: ""
    grad_clip: 5
    batch_size: 2
    num_workers: 4
    pi:
        use: True
        loss_type: 'mse' # sisnr or mse
        sup_lambda: 0.1
        uns_lambda: 0.1
        warmup_step: 40000
    locs: [ '2|3' ]
    scheduler:
        use: True
        type: 'ReduceLROnPlateau'
        patience: 4

