# There is two perturbation need to be set in pi-model.
# First one can be set in 'input_transform' of 'solver', which stand for gaussian noise.
# Second one is set in 'sep_out_dropout' of 'model', which stand for dropout part.
# Choose one while training.
data:
    dset: 'wsj0'
    sample_rate: 8000
    segment: 4.0
    uns_dset: 'wsj0-vctk'
    uns_segment: 2.0

model:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: 0
    mask_nonlinear: 'softmax'
    # Perturbation 2: add dropout on sep output
    sep_out_dropout: 0.0

optim:
    type: 'ranger'
    lr: 0.0001
    weight_decay: 0.0

solver:
    exp_name: 'pi_model-pertrub_dropout01-consistency_emb'
    save_dir: './checkpoints/'
    log_dir: './logs/'
    pretrained: '/groups/public/szulin_separation_dataset/pretrained/99.pth'
    pretrained_optim: False
    max_save_num: 1
    epochs: 10
    start_epoch: 0
    resume_exp_name: ""
    resume_optim: ""
    grad_clip: 5
    batch_size: 2
    num_workers: 4
    # Perturbation 1: add gaussian noise on waveform
    # Only need to change 'scale'
    input_transform:
        where: 'wav'
        methods: [ 'noise' ]
        noise:
            scale: 0.05
    # hyparameter for pi-model
    pi:
        use: True
        # loss type, support 'mse' and 'sisnr'
        # If is 'mse', need to config 'locs' for loss location
        # 'sisnr' compute on waveform
        loss_type: 'mse'
        # pi-model loss weight of source domain dataset, 0 won't consider source domain dataset.
        sup_lambda: 0.1
        # pi-model loss weight of target domain dataset
        uns_lambda: 0.1
        # warmup step used in pi-model
        # Please check cal_consistency_weight() in 'src/train_pimt.py'
        warmup_step: 40000
    # location for computing consistency regularization in repersentation
    # format: [ '2|r', '2|r|x', 'mask', ... ]
    # r stand index of R
    # x stand index of X
    # '2|r' means use output of rth repeat block
    # '2|r|x' means use output of rth repeat block and xth res block
    # 'mask' means computing pit-mse loss on mask
    locs: [ '2|3', 'mask' ]
    scheduler:
        use: True
        type: 'ReduceLROnPlateau'
        patience: 4

